name: artifact
  
on:
  push:
    branches:
      - main
      
env: 
  FILE_NAME: hello-server
  
jobs:
  buld-go:
    name: Build Go
    runs-on: ubuntu-latest
    steps: 
    
    - name: Checkout Go code 
      uses: actions/checkout@v4
    
    - name: Build ${{ env.FILE_NAME }} for ubuntu-latest
      run: go build ${{ env.FILE_NAME }}.go 
    
    - name: Build ${{ env.FILE_NAME }} for windows-latest
      run: GOOS=windows GOARSCH=amd64 go build ${{ env.FILE_NAME }}.go 
      
    - name: Upload artifact for linux 
      uses: actions/upload-artifact@v1.0.0
      with: 
        name: linux 
        path: ./${{ env.FILE_NAME }}
      
    - name: upload atifact for windows 
      uses: actions/upload-artifact@v1.0.0
      with:
        name: windows 
        path: ./${{ env.FILE_NAME }}.exe

  deploy-go:
    name: dowload-and-run-linux
    runs-on: ubuntu-latest
    needs: buld-go

    steps:
    - name: Checkout Go code 
      uses: actions/checkout@v4

    - name: Download artifact for linux 
      uses: actions/download-artifact@v1.0.0
      with: 
        name: linux 
        path: ./${{ env.FILE_NAME }}

    - name: run ubuntu
      run: |
        ls -l 
        pwd
        chmod 755 run.sh
        ./run.sh
        ls -l 
        
    
